---
bind_dnssec_validation: false
bind_zones:
  - forwarders:
      - 10.11.0.1
      - 10.11.0.2
    ipv6_networks:
      - 2001:db9::/48
    name: example.com
    networks:
      - 192.0.2
  - forwarders:
      - 10.11.0.1
      - 10.11.0.2
    ipv6_networks:
      - 2001:db8::/48
    name: acme-inc.com
    networks:
      - "10.11"
    type: forward
